![Python](https://img.shields.io/badge/Python-3.10-blue)
![Transformers](https://img.shields.io/badge/HuggingFace-Transformers-yellow)
![GPU](https://img.shields.io/badge/AMD-MI300X-red)
![Hackathon](https://img.shields.io/badge/Event-AAIPL-green)

# 🚀 Team Whoop... | AMD AI Premier League Hackathon

> ⚡ Built for high-performance reasoning on **AMD MI300X GPUs**

---

## 🧠 Autonomous Logical Reasoning Agents

We developed a **dual-agent AI system** capable of generating and solving high-quality aptitude questions while strictly adhering to structured JSON formats and latency constraints.

This project focuses on **true reasoning — not retrieval.**

---

## 👨‍💻 Team Members

**Nishant Agarwal — Team Lead**  
Sagar Goyal  
Shauriya Garg  
Brajraj Mahajan  

---

## 🎯 Problem Statement

Design autonomous AI agents that can:

✅ Generate logically sound aptitude questions  
✅ Solve them accurately  
✅ Follow strict JSON formats  
✅ Operate within latency limits  
✅ Avoid retrieval-based shortcuts (No RAG)

---

## ⚡ Our Solution

We engineered a **closed-loop reasoning system** consisting of two intelligent agents that continuously validate structured intelligence.

---

## 🔹 Q-Agent — Question Generator

- Produces high-difficulty aptitude questions  
- Maintains strict JSON formatting  
- Automatically filters invalid outputs  
- Ensures topic diversity:
  - Blood Relations  
  - Seating Arrangements  
  - Syllogisms  
  - Alphanumeric Series  

👉 Designed to challenge even strong problem solvers.

---

## 🔹 A-Agent — Answer Solver

- Solves unseen questions generated by Q-Agent  
- Provides concise reasoning (<100 words)  
- Optimized for deterministic logical inference  
- Minimizes hallucinations  

👉 Built for accuracy, speed, and consistency.

---

## 🏗 System Architecture

```
Topics → Q-Agent → Validation → Filtered Questions → A-Agent → Answers
```

### Pipeline Strengths

✅ Synthetic structured prompting  
✅ Self-validation layer  
✅ Format enforcement  
✅ Latency-aware inference  
✅ GPU-optimized execution  

---

## 🚀 Performance Highlights

- ⚡ Question Generation: **< 10 seconds**
- 🎯 High format accuracy
- 🧩 Strong logical consistency
- 🔥 Optimized for **AMD MI300X accelerators**

---

## 📂 Repository Structure

```
AAIPL/
│
├── agents/
│   ├── question_agent.py
│   ├── answer_agent.py
│
├── assets/
│   └── topics.json
│
├── outputs/
│   ├── questions.json
│   ├── filtered_questions.json
│   └── answers.json
```

---

## ▶️ How to Run

### ✅ Generate Questions

```bash
python -m agents.question_agent --num_questions 10
```

Outputs:

- `questions.json`
- `filtered_questions.json`

---

### ✅ Generate Answers

```bash
python -m agents.answer_agent
```

Output:

```
outputs/answers.json
```

---

## 📊 Output Format

### Question JSON

```json
{
  "topic": "...",
  "question": "...",
  "choices": {
    "A": "...",
    "B": "...",
    "C": "...",
    "D": "..."
  },
  "answer": "A",
  "explanation": "brief explanation"
}
```

---

### Answer JSON

```json
{
  "answer": "A",
  "reasoning": "brief logical reasoning"
}
```

---

## 🔐 Constraints Followed

✔ No Retrieval-Augmented Generation (RAG)  
✔ No external databases  
✔ Strict format compliance  
✔ Latency-aware design  
✔ Model-driven reasoning only  

---

## 💡 Key Innovations

### 🔥 Closed-Loop Intelligence
Q-Agent challenges A-Agent, creating a system that naturally improves reasoning quality.

### 🔥 Structured Prompt Engineering
Prevents chain-of-thought leakage while preserving answer accuracy.

### 🔥 Difficulty-Aware Generation
Produces non-trivial yet logically solvable questions.

---

## 🏆 Why Our Approach Stands Out

Instead of treating generation and solving as isolated tasks, we built a **self-improving reasoning ecosystem**.

👉 Harder questions  
👉 Smarter answers  
👉 Cleaner outputs  

A system designed not just to function — but to compete.

---

## 🔮 Future Scope

- Adaptive difficulty scaling  
- Multi-hop reasoning  
- Real-time evaluation loops  
- Larger reasoning models  

---

# ⭐ Team Whoop...
## Engineering Intelligence. Scaling Reasoning.
